"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import os
import sys

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Try to get from Environment (Render), fallback to insecure key for local dev only
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*=%kv(gli^8+&1%1*!$n)5)5(w*rx+x9u**pkt=rl%kokgndcf')

# SECURITY WARNING: don't run with debug turned on in production!
# On Render, set DEBUG environment variable to 'False'
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Allowed Hosts
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# --- PRODUCTION SECURITY HARDENING ---
if not DEBUG:
    # 1. Force HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # 2. HSTS (HTTP Strict Transport Security)
    # Tells browsers to ONLY use HTTPS for the next year
    SECURE_HSTS_SECONDS = 31536000 
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 3. Trust Proxy Headers (Required for Render/Cloudflare)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 4. CSRF Trusted Origins (For Render)
    if 'RENDER_EXTERNAL_URL' in os.environ:
        CSRF_TRUSTED_ORIGINS = [os.environ.get('RENDER_EXTERNAL_URL')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.converter',
    'django_cleanup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Add WhiteNoise for static files!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.converter.context_processors.daily_usage_stats',  # Custom Usage Stats
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok' # Set to Thailand Time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Development: where static files are kept
STATICFILES_DIRS = [BASE_DIR / 'static']

# Production: where static files are collected to
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Enable WhiteNoise's compressed static files storage
# This allows the app to serve its own static files efficiently without Nginx config!
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CloudConvert Configuration (V.2 API)
# Priority: Environment Variable > Hardcoded Key
import os
CLOUDCONVERT_API_KEY = os.environ.get('CLOUDCONVERT_API_KEY', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZWRlOGFmMjRkNjk5MzU5NzhiYWM4ODJiZmRhNmU4YjI3NGQxODViMmU1Y2M1OTY4M2M4ZGEzOTg3OThmYzI1ZjAzZTVmMzJlOWJjZjUxMDIiLCJpYXQiOjE3NzAyMDkyOTkuNTgyNTQ5LCJuYmYiOjE3NzAyMDkyOTkuNTgyNTUsImV4cCI6NDkyNTg4Mjg5OS41NzY5MjUsInN1YiI6IjM1MjM3Mjc2Iiwic2NvcGVzIjpbInVzZXIucmVhZCIsInVzZXIud3JpdGUiLCJ3ZWJob29rLnJlYWQiLCJ3ZWJob29rLndyaXRlIiwidGFzay53cml0ZSIsInRhc2sucmVhZCIsInByZXNldC5yZWFkIiwicHJlc2V0LndyaXRlIl19.fLQPJMDA0eGFq3OHdTL-w6VgmO0xz34dVjJVn-FvzgRqPzwDZ8Davdh03jEff5n69povOS_4vSBQ2apilfHnSzYIt5pbshBT9-BzUgzZOrGnx8TvCQSE_b1VEDpz8QMaCw8abQU93Lw0uC22EaM7lDjsoteOaMfRHMoUZGMszRY9X-5nObgC7w8aSZAOKl81cavSxy4ILfizVWX7JzZxGn3STH3pzssuor5fOEVVFQcAD2TbHvhc1U_CwiOZENLTMKV3tsANWSlHfcdbpuLLMC3kUpQgLRsfbp81bVUWYd5Sro0i6Kd0lG9YVvdh7nW1mGFuLkDLivQPQ9-0JpoDY_RBGinu-E1Gf9Hd0okAzu20gZj6ybwZXdpveBekFIwQ2Fo57fGgGYoE-B2UZyo8RiQl-45Gvz5vL6izTw8CaNabwb92D6Sbxfwi1v3SrtCm6KSbh-wKeoQBcd4UHa5AOUe5wQv7gSVB0CGQEFuvRfbVtzJDrqMtTpJeft9QGxJcX0WSB7ih2VCHwl50D3h0TtS1oUyG9UXFXGoIgtNxn-rfm_pYK46RfLq4mqIcw5YrlhBnW9phAr0_xI20cjVHZUGVezgAsk-nlTlVKvIocpkPlp8nmZgYAnCVZQN5kiDScnHOaJkaihlwi_NFmsKMOSBKle96bqV05vGtIOeVWmw')
CLOUDCONVERT_SANDBOX = False # Set to True if using sandbox API

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
