# Generated by Django 5.0.1 on 2026-02-05 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_dailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=2000)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
